<template>
<div class="loading-spinner">
  <div class="loadingio-spinner-spinner-fs3wx2jbqyr">
    <div class="ldio-3pu59cjlwmh">
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
    </div>
  </div>
</div>
</template>

<script>
export default {
  
}
</script>

<style lang="scss" scoped>
@keyframes ldio-3pu59cjlwmh {
  0% { opacity: 1 }
  100% { opacity: 0 }
}
.ldio-3pu59cjlwmh div {
  left: 48px;
  top: 23.5px;
  position: absolute;
  animation: ldio-3pu59cjlwmh linear 1s infinite;
  background: #f36b2b;
  width: 4px;
  height: 13px;
  border-radius: 2px / 2.6px;
  transform-origin: 2px 26.5px;
}.ldio-3pu59cjlwmh div:nth-child(1) {
  transform: rotate(0deg);
  animation-delay: -0.9166666666666666s;
  background: #f36b2b;
}.ldio-3pu59cjlwmh div:nth-child(2) {
  transform: rotate(30deg);
  animation-delay: -0.8333333333333334s;
  background: #f36b2b;
}.ldio-3pu59cjlwmh div:nth-child(3) {
  transform: rotate(60deg);
  animation-delay: -0.75s;
  background: #f36b2b;
}.ldio-3pu59cjlwmh div:nth-child(4) {
  transform: rotate(90deg);
  animation-delay: -0.6666666666666666s;
  background: #f36b2b;
}.ldio-3pu59cjlwmh div:nth-child(5) {
  transform: rotate(120deg);
  animation-delay: -0.5833333333333334s;
  background: #f36b2b;
}.ldio-3pu59cjlwmh div:nth-child(6) {
  transform: rotate(150deg);
  animation-delay: -0.5s;
  background: #f36b2b;
}.ldio-3pu59cjlwmh div:nth-child(7) {
  transform: rotate(180deg);
  animation-delay: -0.4166666666666667s;
  background: #f36b2b;
}.ldio-3pu59cjlwmh div:nth-child(8) {
  transform: rotate(210deg);
  animation-delay: -0.3333333333333333s;
  background: #f36b2b;
}.ldio-3pu59cjlwmh div:nth-child(9) {
  transform: rotate(240deg);
  animation-delay: -0.25s;
  background: #f36b2b;
}.ldio-3pu59cjlwmh div:nth-child(10) {
  transform: rotate(270deg);
  animation-delay: -0.16666666666666666s;
  background: #f36b2b;
}.ldio-3pu59cjlwmh div:nth-child(11) {
  transform: rotate(300deg);
  animation-delay: -0.08333333333333333s;
  background: #f36b2b;
}.ldio-3pu59cjlwmh div:nth-child(12) {
  transform: rotate(330deg);
  animation-delay: 0s;
  background: #f36b2b;
}
.loadingio-spinner-spinner-fs3wx2jbqyr {
  margin: 0 auto;
  width: 80px;
  height: 80px;
  display: inline-block;
  overflow: hidden;
  background: rgba(255, 255, 255, 0); /*추후수정가능한부분*/
  transform : scale(0.6); /*추후수정가능한부분*/
 border-radius:12px;
}
.ldio-3pu59cjlwmh {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(0.8);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-3pu59cjlwmh div { box-sizing: content-box; }
.loading-spinner{
  padding: 50px 0;
  text-align: center;
}
/* generated by https://loading.io/ */
</style>
